version: "3.9"
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-west-2
  terraform:
    image: terraform_test:1.0.0
    container_name: terraform_test
    user: root
    stdin_open: true
    tty: true
    build: 
      context: .
    volumes: 
        - ./tf:/home